# filesystem_watcher.py - Monitors Inbox folder for new files
import logging
import sys
import time
import shutil
import argparse
from pathlib import Path
from datetime import datetime
from watchdog.observers.polling import PollingObserver
from watchdog.events import FileSystemEventHandler

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('FileSystemWatcher')


class DropFolderHandler(FileSystemEventHandler):
    """Handler for files dropped into the Inbox folder"""

    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.needs_action = self.vault_path / 'Needs_Action'
        self.needs_action.mkdir(parents=True, exist_ok=True)

    def on_created(self, event):
        if event.is_directory:
            return
        source = Path(event.src_path)

        # Skip hidden files and temp files
        if source.name.startswith('.') or source.name.startswith('~'):
            return

        logger.info(f'New file detected: {source.name}')

        # Create metadata file in Needs_Action
        self.create_metadata(source)

    def create_metadata(self, source: Path):
        """Create action file with metadata about the dropped file"""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_name = source.stem.replace(' ', '_')[:30]
        meta_filename = f'FILE_{timestamp}_{safe_name}.md'
        meta_path = self.needs_action / meta_filename

        # Get file stats
        try:
            stat = source.stat()
            size = stat.st_size
            created = datetime.fromtimestamp(stat.st_ctime).isoformat()
        except Exception:
            size = 0
            created = datetime.now().isoformat()

        content = f'''---
type: file_drop
original_name: {source.name}
original_path: {source}
size_bytes: {size}
detected_at: {datetime.now().isoformat()}
status: pending
priority: normal
---

# New File Dropped

A new file has been added to the Inbox folder and requires processing.

## File Details
- **Filename**: {source.name}
- **Size**: {size} bytes
- **Location**: {source}
- **Detected**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Suggested Actions
- [ ] Review file contents
- [ ] Categorize the file
- [ ] Process according to file type
- [ ] Move to appropriate location when done

---
*Generated by FileSystemWatcher*
'''
        meta_path.write_text(content)
        logger.info(f'Created action file: {meta_path.name}')


def run_once(vault_path: Path):
    """Single check mode - process existing files in Inbox and exit"""
    start_time = time.time()
    inbox_path = vault_path / 'Inbox'

    logger.info('Running Filesystem Watcher (once mode)...')
    logger.info(f'Checking: {inbox_path}')

    handler = DropFolderHandler(str(vault_path))
    processed = 0

    # Process all existing files in Inbox
    for file_path in inbox_path.iterdir():
        if file_path.is_file() and not file_path.name.startswith('.') and not file_path.name.startswith('~'):
            logger.info(f'Processing: {file_path.name}')
            handler.create_metadata(file_path)
            processed += 1

    elapsed = time.time() - start_time
    if processed > 0:
        logger.info(f'Processed {processed} file(s) in {elapsed:.2f} seconds')
    else:
        logger.info(f'No new files to process (completed in {elapsed:.2f} seconds)')

    return processed


def main():
    """Main entry point for the file system watcher"""
    parser = argparse.ArgumentParser(description='Filesystem Watcher - Monitor Inbox for new files')
    parser.add_argument('--once', action='store_true', help='Check once and exit immediately')
    parser.add_argument('--vault', type=str, help='Path to AI Employee Vault')
    args = parser.parse_args()

    # Default vault path
    default_vault = Path(__file__).parent.parent.parent.parent / 'AI_Employee_Vault'
    vault_path = Path(args.vault) if args.vault else default_vault

    inbox_path = vault_path / 'Inbox'

    if not inbox_path.exists():
        logger.error(f'Inbox folder not found: {inbox_path}')
        sys.exit(1)

    if args.once:
        # Single check mode - fast execution for demos
        processed = run_once(vault_path)
        sys.exit(0)

    # Continuous monitoring mode
    logger.info(f'Starting File System Watcher')
    logger.info(f'Vault path: {vault_path}')
    logger.info(f'Watching: {inbox_path}')
    logger.info(f'Actions will be created in: {vault_path / "Needs_Action"}')

    event_handler = DropFolderHandler(str(vault_path))
    # Use PollingObserver for WSL2/cross-platform compatibility
    observer = PollingObserver(timeout=2)
    observer.schedule(event_handler, str(inbox_path), recursive=False)
    observer.start()

    logger.info('Watcher is now running. Press Ctrl+C to stop.')

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        logger.info('Stopping watcher...')
        observer.stop()
    observer.join()
    logger.info('Watcher stopped.')


if __name__ == '__main__':
    main()
